version: '3'
services:
  app:
    image: udemy-react-go-app
    ports:
      - "3000:3000"
    networks:
      - udemy-react-go-postgres
    volumes:
      - ./client:/app
      -
  api:
    image: udemy-react-go-api
    ports:
      - "8080:8080"
    networks:
      - udemy-react-go-postgres
    depends_on:
      - postgres
      -
  db:
    image: postgres
    container_name: udemy-react-go-db
    ports:
      - "5432:5432"
    networks:
      - udemy-react-go-postgres
    volumes:
      - database-data:/var/lib/postgresql/data/
    env_file:
      - .env
      -
volumes:
  database-data:
networks:
  udemy-react-go-postgres:
    driver: bridge